# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [ ]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import random

### Exercício 1

In [4]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

In [5]:
# Array NumPy
array = np.arange(1000000)

# Lista
lst = list(range(1000000))

In [6]:
# Multiplicando por 2 e medindo o tempo de execução
import time
a = 2

# Array
begin_array = time.time()
new_array = array * a
end_array = time.time()
print(end_array - begin_array)

print('-='*60)

# List
begin_lst = time.time()
new_lst = [x * 2 for x in lst]
end_lst = time.time()
print(end_lst - begin_lst)

0.0049932003021240234
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
0.17812514305114746


### Exercício 2

In [7]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [8]:
array = np.arange(10)
print(array)
array[5:8] = 0
print(array)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 0 0 0 8 9]


### Exercício 3

In [9]:
# Crie um array de 3 dimensões e imprima a dimensão 1 

In [10]:
array = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [11,3,0]]])
print(array)
print(array.ndim) #Dimensão

print('-='*60)

array[0]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11  3  0]]]
3
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
y = np.zeros((2, 3, 4))
y.ndim

3

### Exercício 4

In [12]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

In [13]:
matriz = np.array([[1,2,3], [9,8,7], [5,6,4]])
print(matriz)

print('-='*60)

# Terceira linha da matriz
print(matriz[2])

print('-='*60)

#Primeira e segunda linhas & segunda e terceira colunas
print(matriz[:2, 1:])

[[1 2 3]
 [9 8 7]
 [5 6 4]]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[5 6 4]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[[2 3]
 [8 7]]


### Exercício 5

In [14]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [16]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [17]:
for x, y, c in zip(xarr,yarr,cond):
    print(x,y,c)

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


In [18]:
lst = []
for x, y, c in zip(xarr,yarr,cond):
    if c == True:
        lst.append(x)
    else:
        lst.append(y)
lst

[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [19]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

In [20]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.save('array_A', A)

In [22]:
B = np.load('array_A.npy')
B

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Exercício 8

In [23]:
# Considerando a série abaixo, imprima os valores únicos na série
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [24]:
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [25]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [26]:
data = resp.json()
data[0]['title']

'BUG: UnboundLocalError on `df.to_string(max_rows=0)`'

In [27]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

number                                              title  \
0    35394  BUG: UnboundLocalError on `df.to_string(max_ro...   
1    35393                Matplotlib 3.3 compatibility fixups   
2    35392  BUG: Index.get_indexer_non_unique misbehaves w...   
3    35389  ENH: Request for `Index.to_string` & `MultiInd...   
4    35388  BUG: timezone-aware DatetimeIndex doesn't hand...   
5    35387  Display dataframe name or title when using dis...   
6    35386  CLN: resolve isort mypy import confilict test_...   
7    35385                                         fix #35227   
8    35384  ENH: The parameter merge_cells parameter in fu...   
9    35382  BUG: Inconsistent ordering of rows when mergin...   
10   35381                                    Storage options   
11   35380  CLN: resolve isort mypy import confilict test_...   
12   35379     DOC: Expanded Using a Docker Container section   
13   35378                   DOC:  Data Editing Samples/Guide   
14   35377  [FIX] Handle decimal and thousand separator in...   
15   35376                          BUG: inconsistant replace   
16   35375                  ENH: Collation argument to to_sql   
17   35373  ENH: Add validation checks for non-unique merg...   
18   35372  BUG: Pandas Read_html can't get values from ta...   
19   35370  BUG: Categorical data is not correctly plotted...   
20   35369  BUG: df reassignment following reorder_categor...   
21   35368  DOC: Fix heading capitalization in doc/source/...   
22   35367  DOC: Rethink recommending eval/query in "Enhan...   
23   35366               ENH: Allow to group by an empty list   
24   35365  BUG: read_csv fails with float_precision="roun...   
25   35364  DOC: `to_pickle` arguments for `compression` h...   
26   35363  API: quantile function over columns transposes...   
27   35360  fix bug when combining groupby with resample a...   
28   35359                    REF: implement _apply_blockwise   
29   35357                PERF: BlockManager.equals blockwise   

                                               labels state  
0   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
1   [{'id': 76865106, 'node_id': 'MDU6TGFiZWw3Njg2...  open  
2   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
3   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
4   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
5   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
6                                                  []  open  
7                                                  []  open  
8   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
9   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
10  [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...  open  
11  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
12  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
13  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
14  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
15  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
16  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
17  [{'id': 42670965, 'node_id': 'MDU6TGFiZWw0MjY3...  open  
18  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
19  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
20  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
21  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
22  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
23  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
24  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
25  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
26  [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...  open  
27                                                 []  open  
28  [{'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc...  open  
29  [{'id': 49094459, 'node_id': 'MDU6TGFiZWw0OTA5...  open

### Exercício 10

In [28]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

In [29]:
import os
os.remove("exercicio10.db") if os.path.exists("exercicio10") else None

In [30]:
import sqlite3

In [31]:
# Criando banco de dados
con = sqlite3.connect('exercicio10.db')

# Criando um cursor para percorrer o banco de dados
cur = con.cursor()

In [32]:
# Criando tabela
sql_table = 'create table courses4'\
'(id integer primary key, '\
'titulo varchar (100), '\
'categoria varchar (140))'

cur.execute(sql_table)

In [33]:
# Cursor para inserir registros
sql_insert = 'insert into courses4 values (?,?,?)'

# Dados
recset = [(1000, 'Ciência de Dados', 'Data Science'),
          (1001, 'Big Data Fundamentos', 'Big Data'),
          (1002, 'Python Fundamentos', 'Análise de Dados')]

# Inserindo os registros
for rec in recset:
    cur.execute(sql_insert, rec)
    
# Gravando os dados no banco de dados
con.commit()

In [34]:
# Consultando a tabela
sql_select = 'select * from courses4'

cur.execute(sql_select)
dados = cur.fetchall()

for linha in dados:
    print('Curso id: %d, Título: %s, Categoria: %s \n' % linha)

Curso id: 1000, Título: Ciência de Dados, Categoria: Data Science 

Curso id: 1001, Título: Big Data Fundamentos, Categoria: Big Data 

Curso id: 1002, Título: Python Fundamentos, Categoria: Análise de Dados 



In [35]:
from pandas import DataFrame
frame = DataFrame(dados)
frame

0                     1                 2
0  1000      Ciência de Dados      Data Science
1  1001  Big Data Fundamentos          Big Data
2  1002    Python Fundamentos  Análise de Dados

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>